s = "Hello World"
print(pow(2, 3, 3))
print(abs(-5))
print(round(3.4))
print(round(4.2161241, 2))
print(s.lower())
print(s.upper())
print(s.find('l'))
print(s.center(20, 'z'))
print(s.isalpha())
print(s.split('l'))
print(s.partition('l'))
print(s.count('l'))
mylist = [1,2,3]
mylist.reverse()
print(mylist)
